---
title: "DATOS DE FELINOS DE cOSTA RICA"
author: "Byron Vargas"
date: '2022-06-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Preparativos  


``` {r}
library(dplyr)
library(sf)
library(ggplot2)
library(plotly)
library(DT)
library(leaflet)

```

```{r}
felinos <-
  st_read(
    "C:/Users/C18272/6 junio/felinos.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"  
    ),
    quiet = TRUE
  )  
```

# Tabla  

``` {r tabla}
felinos %>%
  select(species,
         eventDate,
         stateProvince,
         locality,
         decimalLongitude,
         decimalLatitude) %>%
  st_drop_geometry() %>%
  datatable(
    colnames = c(
      "Especie",
      "Fecha",
      "Provincia",
      "Localidad",
      "Longitud",
      "Latitud"
    ),
      options = list(
        pageLength = 5,
        language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
      )
    )

```
# Gráfico   
